USE master;
GO

-- Verifica daca db exista si o sterge daca da
-- Mai intai seteaza baza de date pe single user pentru a o putea sterge
IF DB_ID('ticketing') IS NOT NULL
BEGIN
    ALTER DATABASE ticketing SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE ticketing; 
END

DROP DATABASE IF EXISTS ticketing;
GO

CREATE DATABASE ticketing;
GO

USE ticketing;
GO

CREATE TABLE COMPANIES(
    COMPANY_ID INT IDENTITY(1,1) PRIMARY KEY,
    COMPANY_NAME VARCHAR(100) NOT NULL
);
GO

CREATE TABLE TEAMS(
    TEAM_ID INT IDENTITY(1,1) PRIMARY KEY,
    TEAM_NAME VARCHAR(100) NOT NULL UNIQUE,
    COMPANY_ID INT FOREIGN KEY REFERENCES COMPANIES(COMPANY_ID)
);
GO

CREATE TABLE USERS (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(100),
    TEAM VARCHAR(100),
    FOREIGN KEY (TEAM) REFERENCES TEAMS(TEAM_NAME)
);
GO

CREATE TABLE STATUSES(
    STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
    STATUS_NAME VARCHAR(50) NOT NULL
);
GO

CREATE TABLE PRIORITIES(
    PRIORITY_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRIORITY_NAME VARCHAR(50) NOT NULL
);
GO

CREATE TABLE INCIDENT_TICKETS(
    TICKET_NUMBER VARCHAR(50) PRIMARY KEY,
    COMPANY_ID INT FOREIGN KEY REFERENCES COMPANIES(COMPANY_ID),
    TEAM_ID INT FOREIGN KEY REFERENCES TEAMS(TEAM_ID),
    STATUS_ID INT FOREIGN KEY REFERENCES STATUSES(STATUS_ID),
    PRIORITY_ID INT FOREIGN KEY REFERENCES PRIORITIES(PRIORITY_ID),
    PROJECT VARCHAR(100),
    ASSIGNED_PERSON VARCHAR(100) FOREIGN KEY REFERENCES USERS(FULL_NAME),
    SERVICE VARCHAR(100),
    DESCRIPTION TEXT,
    NOTES TEXT,
    RESOLUTION TEXT,
    CATEGORY_TIER_1 VARCHAR(100),
    CATEGORY_TIER_2 VARCHAR(100),
    CATEGORY_TIER_3 VARCHAR(100),
    SUBMIT_DATETIME DATETIME,
    RESOLVED_DATETIME DATETIME,
    CLOSED_DATETIME DATETIME,
    LAST_MODIFIED_DATETIME DATETIME,
    ESTIMATED_RESOLUTION_DATETIME DATETIME,
    RESOLUTION_CATEGORY VARCHAR(100),
    PENDING_DURATION INTEGER
);
GO