USE ticketing;
GO

UPDATE INCIDENT_TICKETS
SET 
    STATUS_ID = (SELECT STATUS_ID FROM STATUSES WHERE STATUS_NAME = 'Assigned'),
    LAST_MODIFIED_DATETIME = GETDATE() 
WHERE 
    STATUS_ID = (SELECT STATUS_ID FROM STATUSES WHERE STATUS_NAME = 'Open')
    AND ASSIGNED_PERSON IS NOT NULL 
    AND ASSIGNED_PERSON <> '';
GO